apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry-proxy.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "registry-proxy.name" . }}
    {{- include "registry-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "registry-proxy.name" . }}
    {{- include "registry-proxy.selectorLabels" . | nindent 4 }}
